### ISSUE TITLE
Add shuffle in grandom

### ISSUE THREAD

**Issue by wafuwafu13** [xjh22222228/gosh#16]
I want to add shuffle in [grandom](https://github.com/xjh22222228/gosh#grandom).
https://www.w3schools.com/python/ref_random_shuffle.asp

**Comment by xjh22222228** [comment]
Can you mention PR.

**Comment by wafuwafu13** [comment]
I see You already add shuffle.
https://github.com/xjh22222228/gosh/commit/9a251984f9dcc3626a8968e62cb2a7d39d1ed6cb
